services:
  ismap:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./ismap.db:/app/ismap.db
    environment:
      - DATABASE_URL=sqlite:///ismap.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-supersecretkey}
      - VITE_API_URL=http://localhost:5000
    restart: always
