services:
  - type: web
    name: ismap-scanner
    runtime: docker
    plan: free
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///ismap.db

